# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import engine_pb2 as engine__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HealthStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/engine.Health/Check',
                request_serializer=engine__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=engine__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class HealthServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Check(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=engine__pb2.HealthCheckRequest.FromString,
                    response_serializer=engine__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'engine.Health', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('engine.Health', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Health(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.Health/Check',
            engine__pb2.HealthCheckRequest.SerializeToString,
            engine__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DataEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetState = channel.unary_unary(
                '/engine.DataEngine/GetState',
                request_serializer=engine__pb2.GetStateRequest.SerializeToString,
                response_deserializer=engine__pb2.GetStateResponse.FromString,
                _registered_method=True)
        self.Start = channel.unary_unary(
                '/engine.DataEngine/Start',
                request_serializer=engine__pb2.StartRequest.SerializeToString,
                response_deserializer=engine__pb2.StartResponse.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/engine.DataEngine/Stop',
                request_serializer=engine__pb2.StopRequest.SerializeToString,
                response_deserializer=engine__pb2.StopResponse.FromString,
                _registered_method=True)
        self.LoadReplayData = channel.unary_unary(
                '/engine.DataEngine/LoadReplayData',
                request_serializer=engine__pb2.LoadReplayDataRequest.SerializeToString,
                response_deserializer=engine__pb2.ReplayControlResponse.FromString,
                _registered_method=True)
        self.StartEngine = channel.unary_unary(
                '/engine.DataEngine/StartEngine',
                request_serializer=engine__pb2.StartEngineRequest.SerializeToString,
                response_deserializer=engine__pb2.StartEngineResponse.FromString,
                _registered_method=True)
        self.StopEngine = channel.unary_unary(
                '/engine.DataEngine/StopEngine',
                request_serializer=engine__pb2.StopEngineRequest.SerializeToString,
                response_deserializer=engine__pb2.ReplayControlResponse.FromString,
                _registered_method=True)
        self.SetReplaySpeed = channel.unary_unary(
                '/engine.DataEngine/SetReplaySpeed',
                request_serializer=engine__pb2.SetReplaySpeedRequest.SerializeToString,
                response_deserializer=engine__pb2.ReplayControlResponse.FromString,
                _registered_method=True)
        self.PauseReplay = channel.unary_unary(
                '/engine.DataEngine/PauseReplay',
                request_serializer=engine__pb2.PauseReplayRequest.SerializeToString,
                response_deserializer=engine__pb2.ReplayControlResponse.FromString,
                _registered_method=True)
        self.ResumeReplay = channel.unary_unary(
                '/engine.DataEngine/ResumeReplay',
                request_serializer=engine__pb2.ResumeReplayRequest.SerializeToString,
                response_deserializer=engine__pb2.ReplayControlResponse.FromString,
                _registered_method=True)
        self.StepReplay = channel.unary_unary(
                '/engine.DataEngine/StepReplay',
                request_serializer=engine__pb2.StepReplayRequest.SerializeToString,
                response_deserializer=engine__pb2.ReplayControlResponse.FromString,
                _registered_method=True)
        self.StopReplay = channel.unary_unary(
                '/engine.DataEngine/StopReplay',
                request_serializer=engine__pb2.StopReplayRequest.SerializeToString,
                response_deserializer=engine__pb2.ReplayControlResponse.FromString,
                _registered_method=True)
        self.ForceStopReplay = channel.unary_unary(
                '/engine.DataEngine/ForceStopReplay',
                request_serializer=engine__pb2.ForceStopReplayRequest.SerializeToString,
                response_deserializer=engine__pb2.ReplayControlResponse.FromString,
                _registered_method=True)
        self.ListInstruments = channel.unary_unary(
                '/engine.DataEngine/ListInstruments',
                request_serializer=engine__pb2.ListInstrumentsRequest.SerializeToString,
                response_deserializer=engine__pb2.ListInstrumentsResponse.FromString,
                _registered_method=True)
        self.ListAllListedSymbols = channel.unary_unary(
                '/engine.DataEngine/ListAllListedSymbols',
                request_serializer=engine__pb2.ListAllListedSymbolsRequest.SerializeToString,
                response_deserializer=engine__pb2.ListAllListedSymbolsResponse.FromString,
                _registered_method=True)
        self.GetPortfolio = channel.unary_unary(
                '/engine.DataEngine/GetPortfolio',
                request_serializer=engine__pb2.GetPortfolioRequest.SerializeToString,
                response_deserializer=engine__pb2.GetPortfolioResponse.FromString,
                _registered_method=True)
        self.VenueLogin = channel.unary_unary(
                '/engine.DataEngine/VenueLogin',
                request_serializer=engine__pb2.VenueLoginRequest.SerializeToString,
                response_deserializer=engine__pb2.VenueLoginResponse.FromString,
                _registered_method=True)
        self.VenueLogout = channel.unary_unary(
                '/engine.DataEngine/VenueLogout',
                request_serializer=engine__pb2.VenueLogoutRequest.SerializeToString,
                response_deserializer=engine__pb2.VenueControlResponse.FromString,
                _registered_method=True)
        self.SubscribeMarketData = channel.unary_unary(
                '/engine.DataEngine/SubscribeMarketData',
                request_serializer=engine__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=engine__pb2.SubscribeResponse.FromString,
                _registered_method=True)
        self.UnsubscribeMarketData = channel.unary_unary(
                '/engine.DataEngine/UnsubscribeMarketData',
                request_serializer=engine__pb2.UnsubscribeRequest.SerializeToString,
                response_deserializer=engine__pb2.SubscribeResponse.FromString,
                _registered_method=True)
        self.SetExecutionMode = channel.unary_unary(
                '/engine.DataEngine/SetExecutionMode',
                request_serializer=engine__pb2.SetExecutionModeRequest.SerializeToString,
                response_deserializer=engine__pb2.SetExecutionModeResponse.FromString,
                _registered_method=True)
        self.ForceAccountSnapshot = channel.unary_unary(
                '/engine.DataEngine/ForceAccountSnapshot',
                request_serializer=engine__pb2.ForceAccountSnapshotRequest.SerializeToString,
                response_deserializer=engine__pb2.ForceAccountSnapshotResponse.FromString,
                _registered_method=True)
        self.SubscribeBackendEvents = channel.unary_stream(
                '/engine.DataEngine/SubscribeBackendEvents',
                request_serializer=engine__pb2.SubscribeBackendEventsReq.SerializeToString,
                response_deserializer=engine__pb2.BackendEvent.FromString,
                _registered_method=True)
        self.SubmitSecret = channel.unary_unary(
                '/engine.DataEngine/SubmitSecret',
                request_serializer=engine__pb2.SubmitSecretReq.SerializeToString,
                response_deserializer=engine__pb2.SubmitSecretRes.FromString,
                _registered_method=True)
        self.PlaceOrder = channel.unary_unary(
                '/engine.DataEngine/PlaceOrder',
                request_serializer=engine__pb2.PlaceOrderReq.SerializeToString,
                response_deserializer=engine__pb2.PlaceOrderRes.FromString,
                _registered_method=True)
        self.CancelOrder = channel.unary_unary(
                '/engine.DataEngine/CancelOrder',
                request_serializer=engine__pb2.CancelOrderReq.SerializeToString,
                response_deserializer=engine__pb2.CancelOrderRes.FromString,
                _registered_method=True)
        self.ModifyOrder = channel.unary_unary(
                '/engine.DataEngine/ModifyOrder',
                request_serializer=engine__pb2.ModifyOrderReq.SerializeToString,
                response_deserializer=engine__pb2.ModifyOrderRes.FromString,
                _registered_method=True)
        self.GetOrderStatus = channel.unary_unary(
                '/engine.DataEngine/GetOrderStatus',
                request_serializer=engine__pb2.GetOrderStatusReq.SerializeToString,
                response_deserializer=engine__pb2.GetOrderStatusRes.FromString,
                _registered_method=True)
        self.GetOrders = channel.unary_unary(
                '/engine.DataEngine/GetOrders',
                request_serializer=engine__pb2.GetOrdersReq.SerializeToString,
                response_deserializer=engine__pb2.GetOrdersRes.FromString,
                _registered_method=True)
        self.RegisterLiveStrategy = channel.unary_unary(
                '/engine.DataEngine/RegisterLiveStrategy',
                request_serializer=engine__pb2.RegisterLiveStrategyReq.SerializeToString,
                response_deserializer=engine__pb2.RegisterLiveStrategyRes.FromString,
                _registered_method=True)
        self.StartLiveStrategy = channel.unary_unary(
                '/engine.DataEngine/StartLiveStrategy',
                request_serializer=engine__pb2.StartLiveStrategyReq.SerializeToString,
                response_deserializer=engine__pb2.StartLiveStrategyRes.FromString,
                _registered_method=True)
        self.StopLiveStrategy = channel.unary_unary(
                '/engine.DataEngine/StopLiveStrategy',
                request_serializer=engine__pb2.StopLiveStrategyReq.SerializeToString,
                response_deserializer=engine__pb2.LiveStrategyControlRes.FromString,
                _registered_method=True)
        self.PauseLiveStrategy = channel.unary_unary(
                '/engine.DataEngine/PauseLiveStrategy',
                request_serializer=engine__pb2.PauseLiveStrategyReq.SerializeToString,
                response_deserializer=engine__pb2.LiveStrategyControlRes.FromString,
                _registered_method=True)
        self.ResumeLiveStrategy = channel.unary_unary(
                '/engine.DataEngine/ResumeLiveStrategy',
                request_serializer=engine__pb2.ResumeLiveStrategyReq.SerializeToString,
                response_deserializer=engine__pb2.LiveStrategyControlRes.FromString,
                _registered_method=True)
        self.GetLiveStrategyStatus = channel.unary_unary(
                '/engine.DataEngine/GetLiveStrategyStatus',
                request_serializer=engine__pb2.GetLiveStrategyStatusReq.SerializeToString,
                response_deserializer=engine__pb2.GetLiveStrategyStatusRes.FromString,
                _registered_method=True)
        self.ListLiveStrategies = channel.unary_unary(
                '/engine.DataEngine/ListLiveStrategies',
                request_serializer=engine__pb2.ListLiveStrategiesReq.SerializeToString,
                response_deserializer=engine__pb2.ListLiveStrategiesRes.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/engine.DataEngine/Shutdown',
                request_serializer=engine__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=engine__pb2.ShutdownResponse.FromString,
                _registered_method=True)


class DataEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetState(self, request, context):
        """Legacy/Static
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadReplayData(self, request, context):
        """Nautilus Replay Control
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartEngine(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopEngine(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetReplaySpeed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseReplay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeReplay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StepReplay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopReplay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForceStopReplay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListInstruments(self, request, context):
        """Catalog
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAllListedSymbols(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPortfolio(self, request, context):
        """Portfolio
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VenueLogin(self, request, context):
        """Live Venue / Market Data (Phase 8)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VenueLogout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeMarketData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnsubscribeMarketData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetExecutionMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForceAccountSnapshot(self, request, context):
        """issue #29 Slice 2': force the backend to re-emit the current account snapshot
        (dedup-bypassing) on SubscribeBackendEvents. Fire-and-forget ack — the snapshot
        itself returns via the existing AccountEvent stream, NOT inline. Rust calls this
        right after applying the ExecutionModeChanged→Live reset that clears PortfolioState.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeBackendEvents(self, request, context):
        """Phase 9 Step 0: Backend Event Transport (server-streaming).
        Reverse-direction control-plane channel: server pushes BackendEvent to the UI.
        Must be added before other Phase 9 RPCs (everything depends on this transport).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitSecret(self, request, context):
        """Phase 9 Step 1: secret relay (Tachibana second-password).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaceOrder(self, request, context):
        """Phase 9 Step 2: manual order execution facade (mock-backed for now; ADR §7).
        Write RPCs reject in Replay mode (error_code=EXECUTION_MODE_PRECONDITION) and
        require a live runner (error_code=VENUE_LOGIN_REQUIRED). On success they both
        return the resulting OrderEvent inline AND push it on SubscribeBackendEvents.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModifyOrder(self, request, context):
        """Phase 9 Step 4: modify (price/qty). Tachibana = CLMKabuCorrectOrder (atomic);
        kabu = cancel→new conversion in the adapter (Step 6, non-atomic; UI warns).
        Step 4 wires the full path through the mock adapter's modify_order.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrders(self, request, context):
        """Phase 9 Step 8 §3.8: list the backend's currently-tracked working orders.
        Used after an auto-restart to reconcile the UI's optimistic order list with
        the backend's truth (a fresh backend has none → UI orders flagged "unknown").
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterLiveStrategy(self, request, context):
        """Phase 10 Step 3: live strategy execution (auto). All unary — the only
        streaming transport remains SubscribeBackendEvents (Phase 9 ADR "single
        channel", M7). RegisterLiveStrategy validates a saved .py and issues an
        opaque strategy_id; StartLiveStrategy promotes it to a Live Auto run.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartLiveStrategy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopLiveStrategy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseLiveStrategy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeLiveStrategy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLiveStrategyStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLiveStrategies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Lifecycle (Step 2: backend-startup-sync)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=engine__pb2.GetStateRequest.FromString,
                    response_serializer=engine__pb2.GetStateResponse.SerializeToString,
            ),
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=engine__pb2.StartRequest.FromString,
                    response_serializer=engine__pb2.StartResponse.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=engine__pb2.StopRequest.FromString,
                    response_serializer=engine__pb2.StopResponse.SerializeToString,
            ),
            'LoadReplayData': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadReplayData,
                    request_deserializer=engine__pb2.LoadReplayDataRequest.FromString,
                    response_serializer=engine__pb2.ReplayControlResponse.SerializeToString,
            ),
            'StartEngine': grpc.unary_unary_rpc_method_handler(
                    servicer.StartEngine,
                    request_deserializer=engine__pb2.StartEngineRequest.FromString,
                    response_serializer=engine__pb2.StartEngineResponse.SerializeToString,
            ),
            'StopEngine': grpc.unary_unary_rpc_method_handler(
                    servicer.StopEngine,
                    request_deserializer=engine__pb2.StopEngineRequest.FromString,
                    response_serializer=engine__pb2.ReplayControlResponse.SerializeToString,
            ),
            'SetReplaySpeed': grpc.unary_unary_rpc_method_handler(
                    servicer.SetReplaySpeed,
                    request_deserializer=engine__pb2.SetReplaySpeedRequest.FromString,
                    response_serializer=engine__pb2.ReplayControlResponse.SerializeToString,
            ),
            'PauseReplay': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseReplay,
                    request_deserializer=engine__pb2.PauseReplayRequest.FromString,
                    response_serializer=engine__pb2.ReplayControlResponse.SerializeToString,
            ),
            'ResumeReplay': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeReplay,
                    request_deserializer=engine__pb2.ResumeReplayRequest.FromString,
                    response_serializer=engine__pb2.ReplayControlResponse.SerializeToString,
            ),
            'StepReplay': grpc.unary_unary_rpc_method_handler(
                    servicer.StepReplay,
                    request_deserializer=engine__pb2.StepReplayRequest.FromString,
                    response_serializer=engine__pb2.ReplayControlResponse.SerializeToString,
            ),
            'StopReplay': grpc.unary_unary_rpc_method_handler(
                    servicer.StopReplay,
                    request_deserializer=engine__pb2.StopReplayRequest.FromString,
                    response_serializer=engine__pb2.ReplayControlResponse.SerializeToString,
            ),
            'ForceStopReplay': grpc.unary_unary_rpc_method_handler(
                    servicer.ForceStopReplay,
                    request_deserializer=engine__pb2.ForceStopReplayRequest.FromString,
                    response_serializer=engine__pb2.ReplayControlResponse.SerializeToString,
            ),
            'ListInstruments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListInstruments,
                    request_deserializer=engine__pb2.ListInstrumentsRequest.FromString,
                    response_serializer=engine__pb2.ListInstrumentsResponse.SerializeToString,
            ),
            'ListAllListedSymbols': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAllListedSymbols,
                    request_deserializer=engine__pb2.ListAllListedSymbolsRequest.FromString,
                    response_serializer=engine__pb2.ListAllListedSymbolsResponse.SerializeToString,
            ),
            'GetPortfolio': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPortfolio,
                    request_deserializer=engine__pb2.GetPortfolioRequest.FromString,
                    response_serializer=engine__pb2.GetPortfolioResponse.SerializeToString,
            ),
            'VenueLogin': grpc.unary_unary_rpc_method_handler(
                    servicer.VenueLogin,
                    request_deserializer=engine__pb2.VenueLoginRequest.FromString,
                    response_serializer=engine__pb2.VenueLoginResponse.SerializeToString,
            ),
            'VenueLogout': grpc.unary_unary_rpc_method_handler(
                    servicer.VenueLogout,
                    request_deserializer=engine__pb2.VenueLogoutRequest.FromString,
                    response_serializer=engine__pb2.VenueControlResponse.SerializeToString,
            ),
            'SubscribeMarketData': grpc.unary_unary_rpc_method_handler(
                    servicer.SubscribeMarketData,
                    request_deserializer=engine__pb2.SubscribeRequest.FromString,
                    response_serializer=engine__pb2.SubscribeResponse.SerializeToString,
            ),
            'UnsubscribeMarketData': grpc.unary_unary_rpc_method_handler(
                    servicer.UnsubscribeMarketData,
                    request_deserializer=engine__pb2.UnsubscribeRequest.FromString,
                    response_serializer=engine__pb2.SubscribeResponse.SerializeToString,
            ),
            'SetExecutionMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetExecutionMode,
                    request_deserializer=engine__pb2.SetExecutionModeRequest.FromString,
                    response_serializer=engine__pb2.SetExecutionModeResponse.SerializeToString,
            ),
            'ForceAccountSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.ForceAccountSnapshot,
                    request_deserializer=engine__pb2.ForceAccountSnapshotRequest.FromString,
                    response_serializer=engine__pb2.ForceAccountSnapshotResponse.SerializeToString,
            ),
            'SubscribeBackendEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeBackendEvents,
                    request_deserializer=engine__pb2.SubscribeBackendEventsReq.FromString,
                    response_serializer=engine__pb2.BackendEvent.SerializeToString,
            ),
            'SubmitSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitSecret,
                    request_deserializer=engine__pb2.SubmitSecretReq.FromString,
                    response_serializer=engine__pb2.SubmitSecretRes.SerializeToString,
            ),
            'PlaceOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceOrder,
                    request_deserializer=engine__pb2.PlaceOrderReq.FromString,
                    response_serializer=engine__pb2.PlaceOrderRes.SerializeToString,
            ),
            'CancelOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOrder,
                    request_deserializer=engine__pb2.CancelOrderReq.FromString,
                    response_serializer=engine__pb2.CancelOrderRes.SerializeToString,
            ),
            'ModifyOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ModifyOrder,
                    request_deserializer=engine__pb2.ModifyOrderReq.FromString,
                    response_serializer=engine__pb2.ModifyOrderRes.SerializeToString,
            ),
            'GetOrderStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderStatus,
                    request_deserializer=engine__pb2.GetOrderStatusReq.FromString,
                    response_serializer=engine__pb2.GetOrderStatusRes.SerializeToString,
            ),
            'GetOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrders,
                    request_deserializer=engine__pb2.GetOrdersReq.FromString,
                    response_serializer=engine__pb2.GetOrdersRes.SerializeToString,
            ),
            'RegisterLiveStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterLiveStrategy,
                    request_deserializer=engine__pb2.RegisterLiveStrategyReq.FromString,
                    response_serializer=engine__pb2.RegisterLiveStrategyRes.SerializeToString,
            ),
            'StartLiveStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.StartLiveStrategy,
                    request_deserializer=engine__pb2.StartLiveStrategyReq.FromString,
                    response_serializer=engine__pb2.StartLiveStrategyRes.SerializeToString,
            ),
            'StopLiveStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.StopLiveStrategy,
                    request_deserializer=engine__pb2.StopLiveStrategyReq.FromString,
                    response_serializer=engine__pb2.LiveStrategyControlRes.SerializeToString,
            ),
            'PauseLiveStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseLiveStrategy,
                    request_deserializer=engine__pb2.PauseLiveStrategyReq.FromString,
                    response_serializer=engine__pb2.LiveStrategyControlRes.SerializeToString,
            ),
            'ResumeLiveStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeLiveStrategy,
                    request_deserializer=engine__pb2.ResumeLiveStrategyReq.FromString,
                    response_serializer=engine__pb2.LiveStrategyControlRes.SerializeToString,
            ),
            'GetLiveStrategyStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLiveStrategyStatus,
                    request_deserializer=engine__pb2.GetLiveStrategyStatusReq.FromString,
                    response_serializer=engine__pb2.GetLiveStrategyStatusRes.SerializeToString,
            ),
            'ListLiveStrategies': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLiveStrategies,
                    request_deserializer=engine__pb2.ListLiveStrategiesReq.FromString,
                    response_serializer=engine__pb2.ListLiveStrategiesRes.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=engine__pb2.ShutdownRequest.FromString,
                    response_serializer=engine__pb2.ShutdownResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'engine.DataEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('engine.DataEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/GetState',
            engine__pb2.GetStateRequest.SerializeToString,
            engine__pb2.GetStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/Start',
            engine__pb2.StartRequest.SerializeToString,
            engine__pb2.StartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/Stop',
            engine__pb2.StopRequest.SerializeToString,
            engine__pb2.StopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadReplayData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/LoadReplayData',
            engine__pb2.LoadReplayDataRequest.SerializeToString,
            engine__pb2.ReplayControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartEngine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/StartEngine',
            engine__pb2.StartEngineRequest.SerializeToString,
            engine__pb2.StartEngineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopEngine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/StopEngine',
            engine__pb2.StopEngineRequest.SerializeToString,
            engine__pb2.ReplayControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetReplaySpeed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/SetReplaySpeed',
            engine__pb2.SetReplaySpeedRequest.SerializeToString,
            engine__pb2.ReplayControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseReplay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/PauseReplay',
            engine__pb2.PauseReplayRequest.SerializeToString,
            engine__pb2.ReplayControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeReplay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/ResumeReplay',
            engine__pb2.ResumeReplayRequest.SerializeToString,
            engine__pb2.ReplayControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StepReplay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/StepReplay',
            engine__pb2.StepReplayRequest.SerializeToString,
            engine__pb2.ReplayControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopReplay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/StopReplay',
            engine__pb2.StopReplayRequest.SerializeToString,
            engine__pb2.ReplayControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForceStopReplay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/ForceStopReplay',
            engine__pb2.ForceStopReplayRequest.SerializeToString,
            engine__pb2.ReplayControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListInstruments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/ListInstruments',
            engine__pb2.ListInstrumentsRequest.SerializeToString,
            engine__pb2.ListInstrumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAllListedSymbols(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/ListAllListedSymbols',
            engine__pb2.ListAllListedSymbolsRequest.SerializeToString,
            engine__pb2.ListAllListedSymbolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPortfolio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/GetPortfolio',
            engine__pb2.GetPortfolioRequest.SerializeToString,
            engine__pb2.GetPortfolioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VenueLogin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/VenueLogin',
            engine__pb2.VenueLoginRequest.SerializeToString,
            engine__pb2.VenueLoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VenueLogout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/VenueLogout',
            engine__pb2.VenueLogoutRequest.SerializeToString,
            engine__pb2.VenueControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeMarketData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/SubscribeMarketData',
            engine__pb2.SubscribeRequest.SerializeToString,
            engine__pb2.SubscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnsubscribeMarketData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/UnsubscribeMarketData',
            engine__pb2.UnsubscribeRequest.SerializeToString,
            engine__pb2.SubscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetExecutionMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/SetExecutionMode',
            engine__pb2.SetExecutionModeRequest.SerializeToString,
            engine__pb2.SetExecutionModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForceAccountSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/ForceAccountSnapshot',
            engine__pb2.ForceAccountSnapshotRequest.SerializeToString,
            engine__pb2.ForceAccountSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeBackendEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/engine.DataEngine/SubscribeBackendEvents',
            engine__pb2.SubscribeBackendEventsReq.SerializeToString,
            engine__pb2.BackendEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/SubmitSecret',
            engine__pb2.SubmitSecretReq.SerializeToString,
            engine__pb2.SubmitSecretRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaceOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/PlaceOrder',
            engine__pb2.PlaceOrderReq.SerializeToString,
            engine__pb2.PlaceOrderRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/CancelOrder',
            engine__pb2.CancelOrderReq.SerializeToString,
            engine__pb2.CancelOrderRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ModifyOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/ModifyOrder',
            engine__pb2.ModifyOrderReq.SerializeToString,
            engine__pb2.ModifyOrderRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrderStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/GetOrderStatus',
            engine__pb2.GetOrderStatusReq.SerializeToString,
            engine__pb2.GetOrderStatusRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/GetOrders',
            engine__pb2.GetOrdersReq.SerializeToString,
            engine__pb2.GetOrdersRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterLiveStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/RegisterLiveStrategy',
            engine__pb2.RegisterLiveStrategyReq.SerializeToString,
            engine__pb2.RegisterLiveStrategyRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartLiveStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/StartLiveStrategy',
            engine__pb2.StartLiveStrategyReq.SerializeToString,
            engine__pb2.StartLiveStrategyRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopLiveStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/StopLiveStrategy',
            engine__pb2.StopLiveStrategyReq.SerializeToString,
            engine__pb2.LiveStrategyControlRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseLiveStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/PauseLiveStrategy',
            engine__pb2.PauseLiveStrategyReq.SerializeToString,
            engine__pb2.LiveStrategyControlRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeLiveStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/ResumeLiveStrategy',
            engine__pb2.ResumeLiveStrategyReq.SerializeToString,
            engine__pb2.LiveStrategyControlRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLiveStrategyStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/GetLiveStrategyStatus',
            engine__pb2.GetLiveStrategyStatusReq.SerializeToString,
            engine__pb2.GetLiveStrategyStatusRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListLiveStrategies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/ListLiveStrategies',
            engine__pb2.ListLiveStrategiesReq.SerializeToString,
            engine__pb2.ListLiveStrategiesRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/Shutdown',
            engine__pb2.ShutdownRequest.SerializeToString,
            engine__pb2.ShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
