# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import engine_pb2 as engine__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HealthStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/engine.Health/Check',
                request_serializer=engine__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=engine__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class HealthServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Check(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=engine__pb2.HealthCheckRequest.FromString,
                    response_serializer=engine__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'engine.Health', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('engine.Health', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Health(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.Health/Check',
            engine__pb2.HealthCheckRequest.SerializeToString,
            engine__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DataEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetState = channel.unary_unary(
                '/engine.DataEngine/GetState',
                request_serializer=engine__pb2.GetStateRequest.SerializeToString,
                response_deserializer=engine__pb2.GetStateResponse.FromString,
                _registered_method=True)
        self.Start = channel.unary_unary(
                '/engine.DataEngine/Start',
                request_serializer=engine__pb2.StartRequest.SerializeToString,
                response_deserializer=engine__pb2.StartResponse.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/engine.DataEngine/Stop',
                request_serializer=engine__pb2.StopRequest.SerializeToString,
                response_deserializer=engine__pb2.StopResponse.FromString,
                _registered_method=True)
        self.LoadReplayData = channel.unary_unary(
                '/engine.DataEngine/LoadReplayData',
                request_serializer=engine__pb2.LoadReplayDataRequest.SerializeToString,
                response_deserializer=engine__pb2.ReplayControlResponse.FromString,
                _registered_method=True)
        self.StartEngine = channel.unary_unary(
                '/engine.DataEngine/StartEngine',
                request_serializer=engine__pb2.StartEngineRequest.SerializeToString,
                response_deserializer=engine__pb2.StartEngineResponse.FromString,
                _registered_method=True)
        self.StopEngine = channel.unary_unary(
                '/engine.DataEngine/StopEngine',
                request_serializer=engine__pb2.StopEngineRequest.SerializeToString,
                response_deserializer=engine__pb2.ReplayControlResponse.FromString,
                _registered_method=True)
        self.SetReplaySpeed = channel.unary_unary(
                '/engine.DataEngine/SetReplaySpeed',
                request_serializer=engine__pb2.SetReplaySpeedRequest.SerializeToString,
                response_deserializer=engine__pb2.ReplayControlResponse.FromString,
                _registered_method=True)
        self.PauseReplay = channel.unary_unary(
                '/engine.DataEngine/PauseReplay',
                request_serializer=engine__pb2.PauseReplayRequest.SerializeToString,
                response_deserializer=engine__pb2.ReplayControlResponse.FromString,
                _registered_method=True)
        self.ResumeReplay = channel.unary_unary(
                '/engine.DataEngine/ResumeReplay',
                request_serializer=engine__pb2.ResumeReplayRequest.SerializeToString,
                response_deserializer=engine__pb2.ReplayControlResponse.FromString,
                _registered_method=True)
        self.StepReplay = channel.unary_unary(
                '/engine.DataEngine/StepReplay',
                request_serializer=engine__pb2.StepReplayRequest.SerializeToString,
                response_deserializer=engine__pb2.ReplayControlResponse.FromString,
                _registered_method=True)
        self.StopReplay = channel.unary_unary(
                '/engine.DataEngine/StopReplay',
                request_serializer=engine__pb2.StopReplayRequest.SerializeToString,
                response_deserializer=engine__pb2.ReplayControlResponse.FromString,
                _registered_method=True)
        self.ForceStopReplay = channel.unary_unary(
                '/engine.DataEngine/ForceStopReplay',
                request_serializer=engine__pb2.ForceStopReplayRequest.SerializeToString,
                response_deserializer=engine__pb2.ReplayControlResponse.FromString,
                _registered_method=True)
        self.ListInstruments = channel.unary_unary(
                '/engine.DataEngine/ListInstruments',
                request_serializer=engine__pb2.ListInstrumentsRequest.SerializeToString,
                response_deserializer=engine__pb2.ListInstrumentsResponse.FromString,
                _registered_method=True)
        self.ListAllListedSymbols = channel.unary_unary(
                '/engine.DataEngine/ListAllListedSymbols',
                request_serializer=engine__pb2.ListAllListedSymbolsRequest.SerializeToString,
                response_deserializer=engine__pb2.ListAllListedSymbolsResponse.FromString,
                _registered_method=True)
        self.GetPortfolio = channel.unary_unary(
                '/engine.DataEngine/GetPortfolio',
                request_serializer=engine__pb2.GetPortfolioRequest.SerializeToString,
                response_deserializer=engine__pb2.GetPortfolioResponse.FromString,
                _registered_method=True)
        self.VenueLogin = channel.unary_unary(
                '/engine.DataEngine/VenueLogin',
                request_serializer=engine__pb2.VenueLoginRequest.SerializeToString,
                response_deserializer=engine__pb2.VenueLoginResponse.FromString,
                _registered_method=True)
        self.VenueLogout = channel.unary_unary(
                '/engine.DataEngine/VenueLogout',
                request_serializer=engine__pb2.VenueLogoutRequest.SerializeToString,
                response_deserializer=engine__pb2.VenueControlResponse.FromString,
                _registered_method=True)
        self.SubscribeMarketData = channel.unary_unary(
                '/engine.DataEngine/SubscribeMarketData',
                request_serializer=engine__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=engine__pb2.SubscribeResponse.FromString,
                _registered_method=True)
        self.UnsubscribeMarketData = channel.unary_unary(
                '/engine.DataEngine/UnsubscribeMarketData',
                request_serializer=engine__pb2.UnsubscribeRequest.SerializeToString,
                response_deserializer=engine__pb2.SubscribeResponse.FromString,
                _registered_method=True)
        self.SetExecutionMode = channel.unary_unary(
                '/engine.DataEngine/SetExecutionMode',
                request_serializer=engine__pb2.SetExecutionModeRequest.SerializeToString,
                response_deserializer=engine__pb2.SetExecutionModeResponse.FromString,
                _registered_method=True)


class DataEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetState(self, request, context):
        """Legacy/Static
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadReplayData(self, request, context):
        """Nautilus Replay Control
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartEngine(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopEngine(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetReplaySpeed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseReplay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeReplay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StepReplay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopReplay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForceStopReplay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListInstruments(self, request, context):
        """Catalog
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAllListedSymbols(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPortfolio(self, request, context):
        """Portfolio
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VenueLogin(self, request, context):
        """Live Venue / Market Data (Phase 8)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VenueLogout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeMarketData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnsubscribeMarketData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetExecutionMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=engine__pb2.GetStateRequest.FromString,
                    response_serializer=engine__pb2.GetStateResponse.SerializeToString,
            ),
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=engine__pb2.StartRequest.FromString,
                    response_serializer=engine__pb2.StartResponse.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=engine__pb2.StopRequest.FromString,
                    response_serializer=engine__pb2.StopResponse.SerializeToString,
            ),
            'LoadReplayData': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadReplayData,
                    request_deserializer=engine__pb2.LoadReplayDataRequest.FromString,
                    response_serializer=engine__pb2.ReplayControlResponse.SerializeToString,
            ),
            'StartEngine': grpc.unary_unary_rpc_method_handler(
                    servicer.StartEngine,
                    request_deserializer=engine__pb2.StartEngineRequest.FromString,
                    response_serializer=engine__pb2.StartEngineResponse.SerializeToString,
            ),
            'StopEngine': grpc.unary_unary_rpc_method_handler(
                    servicer.StopEngine,
                    request_deserializer=engine__pb2.StopEngineRequest.FromString,
                    response_serializer=engine__pb2.ReplayControlResponse.SerializeToString,
            ),
            'SetReplaySpeed': grpc.unary_unary_rpc_method_handler(
                    servicer.SetReplaySpeed,
                    request_deserializer=engine__pb2.SetReplaySpeedRequest.FromString,
                    response_serializer=engine__pb2.ReplayControlResponse.SerializeToString,
            ),
            'PauseReplay': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseReplay,
                    request_deserializer=engine__pb2.PauseReplayRequest.FromString,
                    response_serializer=engine__pb2.ReplayControlResponse.SerializeToString,
            ),
            'ResumeReplay': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeReplay,
                    request_deserializer=engine__pb2.ResumeReplayRequest.FromString,
                    response_serializer=engine__pb2.ReplayControlResponse.SerializeToString,
            ),
            'StepReplay': grpc.unary_unary_rpc_method_handler(
                    servicer.StepReplay,
                    request_deserializer=engine__pb2.StepReplayRequest.FromString,
                    response_serializer=engine__pb2.ReplayControlResponse.SerializeToString,
            ),
            'StopReplay': grpc.unary_unary_rpc_method_handler(
                    servicer.StopReplay,
                    request_deserializer=engine__pb2.StopReplayRequest.FromString,
                    response_serializer=engine__pb2.ReplayControlResponse.SerializeToString,
            ),
            'ForceStopReplay': grpc.unary_unary_rpc_method_handler(
                    servicer.ForceStopReplay,
                    request_deserializer=engine__pb2.ForceStopReplayRequest.FromString,
                    response_serializer=engine__pb2.ReplayControlResponse.SerializeToString,
            ),
            'ListInstruments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListInstruments,
                    request_deserializer=engine__pb2.ListInstrumentsRequest.FromString,
                    response_serializer=engine__pb2.ListInstrumentsResponse.SerializeToString,
            ),
            'ListAllListedSymbols': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAllListedSymbols,
                    request_deserializer=engine__pb2.ListAllListedSymbolsRequest.FromString,
                    response_serializer=engine__pb2.ListAllListedSymbolsResponse.SerializeToString,
            ),
            'GetPortfolio': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPortfolio,
                    request_deserializer=engine__pb2.GetPortfolioRequest.FromString,
                    response_serializer=engine__pb2.GetPortfolioResponse.SerializeToString,
            ),
            'VenueLogin': grpc.unary_unary_rpc_method_handler(
                    servicer.VenueLogin,
                    request_deserializer=engine__pb2.VenueLoginRequest.FromString,
                    response_serializer=engine__pb2.VenueLoginResponse.SerializeToString,
            ),
            'VenueLogout': grpc.unary_unary_rpc_method_handler(
                    servicer.VenueLogout,
                    request_deserializer=engine__pb2.VenueLogoutRequest.FromString,
                    response_serializer=engine__pb2.VenueControlResponse.SerializeToString,
            ),
            'SubscribeMarketData': grpc.unary_unary_rpc_method_handler(
                    servicer.SubscribeMarketData,
                    request_deserializer=engine__pb2.SubscribeRequest.FromString,
                    response_serializer=engine__pb2.SubscribeResponse.SerializeToString,
            ),
            'UnsubscribeMarketData': grpc.unary_unary_rpc_method_handler(
                    servicer.UnsubscribeMarketData,
                    request_deserializer=engine__pb2.UnsubscribeRequest.FromString,
                    response_serializer=engine__pb2.SubscribeResponse.SerializeToString,
            ),
            'SetExecutionMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetExecutionMode,
                    request_deserializer=engine__pb2.SetExecutionModeRequest.FromString,
                    response_serializer=engine__pb2.SetExecutionModeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'engine.DataEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('engine.DataEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/GetState',
            engine__pb2.GetStateRequest.SerializeToString,
            engine__pb2.GetStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/Start',
            engine__pb2.StartRequest.SerializeToString,
            engine__pb2.StartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/Stop',
            engine__pb2.StopRequest.SerializeToString,
            engine__pb2.StopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadReplayData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/LoadReplayData',
            engine__pb2.LoadReplayDataRequest.SerializeToString,
            engine__pb2.ReplayControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartEngine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/StartEngine',
            engine__pb2.StartEngineRequest.SerializeToString,
            engine__pb2.StartEngineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopEngine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/StopEngine',
            engine__pb2.StopEngineRequest.SerializeToString,
            engine__pb2.ReplayControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetReplaySpeed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/SetReplaySpeed',
            engine__pb2.SetReplaySpeedRequest.SerializeToString,
            engine__pb2.ReplayControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseReplay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/PauseReplay',
            engine__pb2.PauseReplayRequest.SerializeToString,
            engine__pb2.ReplayControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeReplay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/ResumeReplay',
            engine__pb2.ResumeReplayRequest.SerializeToString,
            engine__pb2.ReplayControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StepReplay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/StepReplay',
            engine__pb2.StepReplayRequest.SerializeToString,
            engine__pb2.ReplayControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopReplay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/StopReplay',
            engine__pb2.StopReplayRequest.SerializeToString,
            engine__pb2.ReplayControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForceStopReplay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/ForceStopReplay',
            engine__pb2.ForceStopReplayRequest.SerializeToString,
            engine__pb2.ReplayControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListInstruments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/ListInstruments',
            engine__pb2.ListInstrumentsRequest.SerializeToString,
            engine__pb2.ListInstrumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAllListedSymbols(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/ListAllListedSymbols',
            engine__pb2.ListAllListedSymbolsRequest.SerializeToString,
            engine__pb2.ListAllListedSymbolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPortfolio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/GetPortfolio',
            engine__pb2.GetPortfolioRequest.SerializeToString,
            engine__pb2.GetPortfolioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VenueLogin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/VenueLogin',
            engine__pb2.VenueLoginRequest.SerializeToString,
            engine__pb2.VenueLoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VenueLogout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/VenueLogout',
            engine__pb2.VenueLogoutRequest.SerializeToString,
            engine__pb2.VenueControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeMarketData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/SubscribeMarketData',
            engine__pb2.SubscribeRequest.SerializeToString,
            engine__pb2.SubscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnsubscribeMarketData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/UnsubscribeMarketData',
            engine__pb2.UnsubscribeRequest.SerializeToString,
            engine__pb2.SubscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetExecutionMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.DataEngine/SetExecutionMode',
            engine__pb2.SetExecutionModeRequest.SerializeToString,
            engine__pb2.SetExecutionModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
